### ISSUE TITLE
Directly from image_recorder.image.value to numpy ndarray?

### ISSUE THREAD

**Issue by jiapei100** [maartenbreddels/ipywebrtc#112]
Reading your code at [https://ipywebrtc.readthedocs.io/en/latest/ImageRecorder.html](https://ipywebrtc.readthedocs.io/en/latest/ImageRecorder.html).

1. Not sure if we can ignore **PIL**? 

```    im_in = PIL.Image.open(io.BytesIO(image_recorder.image.value))
    im_array = np.array(im_in)[...,:3] # no alpha
```

2. Why do we need to save images as **png** files and save for later widget display???? Won't this make the display much slower??
```console
    # store in image widget
    f = io.BytesIO()
    im_out.save(f, format='png')
    image.value = f.getvalue()
```

**Comment by maartenbreddels** [comment]
> 1. Not sure if we can ignore **PIL**?

what do you mean with that?



> 2\. Why do we need to save images as **png** files and save for later widget display?

Because the image widget want to read images in an image format, png/jpeg/gif. Note that we keep everything in memory, but upload the data via de widget in png format, which will also reduce the amount of traffic.

**Comment by maartenbreddels** [comment]
Since I don't think this is slow, I consider this answered.
