### ISSUE TITLE
JupyterLab 0.33.4: Error: Cannot find module 'jupyter-webrtc/lib/labplugin'

### ISSUE THREAD

**Issue by mprogram** [maartenbreddels/ipywebrtc#14]
In JLab 0.33.4 I'm getting the error(s) in the Chrome console:
`Error: Cannot find module 'jupyter-webrtc/lib/labplugin'`
`Error: Cannot find module 'jupyterlab-volume/'`
though both are installed.

**Comment by SylvainCorlay** [comment]
Did you enable the lab extensions?

**Comment by mprogram** [comment]
Yes, of course, also removed the `staging` directory and re-built the lab. 

`# jupyter labextension list`:
`JupyterLab v0.33.4`
`Known labextensions:`
`   app dir: /usr/share/jupyter/lab`
`...`
`jupyter-webrtc`
`        jupyter-webrtc v0.3.0  enabled  OK`
`...`
`jupyterlab-volume`
`        jupyterlab-volume v0.4.0  enabled  OK`
`...`
`@jupyter-widgets/jupyterlab-manager`
`@jupyter-widgets/jupyterlab-manager v0.36.0 enabled OK`
`...`

Working extensions are (among some): plotlywidget v0.2.0 (plotly.js 1.39.3), bqplot, etc.

It happens in the Chrome console, with no 'yelow' messages in the lab debug log.

**Comment by mprogram** [comment]
I don't know, just a wild guess,, should it be `jupyter-webrtc/lib/labplugin.js` with the `.js` extension in order to work? I've upgraded to JLab to 0.33.5, as also to the most recent IPython, ipykernel, etc. The error is still manifest itself, as also the absence of (some) widgets functionality. I wrote more about it in issue #206 on pythreejs.

**Comment by mprogram** [comment]
See [jupyter-widgets/ipywidgets#2163](https://github.com/jupyter-widgets/ipywidgets/issues/2163) for the `ipywidgets` issue.

**Comment by mprogram** [comment]
No longer the issue after various upgrades, closing. Everything is working as expected, thanks for developing this extension, it works fantastic!
