### ISSUE TITLE
Using undefined reject

### ISSUE THREAD

**Issue by vidartf** [maartenbreddels/ipywebrtc#28]
The `reject` function on [this line](https://github.com/maartenbreddels/ipywebrtc/blob/fc0c5c10fa89c05f1ec7553f962592e812d82788/js/src/webrtc.js#L95) seems undefined. What is it meant to do?

**Comment by martinRenou** [comment]
It's a bug, maybe it was in the callback of a `Promise` that is not there anymore. I'll remove it
