### ISSUE TITLE
Put this github repo in the documentation somewhere

### ISSUE THREAD

**Issue by walchko** [maartenbreddels/ipywebrtc#3]
Please make it easy for people to find the docs ... I googled around and eventually found it. Your [pypi](https://pypi.org/project/ipywebrtc/) page listed the homepage as jupyter.org which isn't helpful.

**Comment by martinRenou** [comment]
I think it's safe to say that it's fixed now 😜 you can take a look at the Readme file

**Comment by walchko** [comment]
thanks :)
