### ISSUE TITLE
Problems In Linux Installation

### ISSUE THREAD

**Issue by iAhmedMaher** [maartenbreddels/ipywebrtc#51]
I wasn't able to use ipywebrtc for Linux. Is it supported? I tried both the conda installation and building from source. Building from source gives the following error:

`Obtaining file:///home/ipywebrtc
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    running egg_info
    running jsdeps
    6.9.0
    6.9.0
    Installing build dependencies with npm.  This may take a while...
    npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
    npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
    npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
    npm WARN lifecycle jupyter-webrtc@0.4.3~prepublish: cannot run in wd jupyter-webrtc@0.4.3 webpack (wd=/home/ipywebrtc/js)
    npm WARN lifecycle jupyter-webrtc@0.4.3~prepare: cannot run in wd jupyter-webrtc@0.4.3 npm run build:lib (wd=/home/ipywebrtc/js)
    npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN jupyter-webrtc@0.4.3 No license field.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
`
`
    audited 7154 packages in 5.29s
    found 26 vulnerabilities (2 low, 19 moderate, 5 high)
      run `npm audit fix` to fix them, or `npm audit` for details
    rebuilding js and css failed
    missing files: ['/home/ipywebrtc/ipywebrtc/static/extension.js', '/home/ipywebrtc/ipywebrtc/static/index.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ipywebrtc/setup.py", line 177, in <module>
        setup(**setup_args)
      File "/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ipywebrtc/setup.py", line 45, in run
        raise e
      File "/home/ipywebrtc/setup.py", line 38, in run
        self.distribution.run_command('jsdeps')
      File "/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ipywebrtc/setup.py", line 118, in run
        raise ValueError(msg)
    ValueError: Missing file: /home/ipywebrtc/ipywebrtc/static/extension.js`

Any idea?

**Comment by SylvainCorlay** [comment]
ipywebrtc works well on linux.

The error that you are seeing concerns development installations where we rebuild upon changes in the file system.

**Comment by SylvainCorlay** [comment]
Feel free to ask any question here with the errors that you are seeing in the front-end.

Also, there is a chat room where you may get some help: https://gitter.im/QuantStack/Lobby
