### ISSUE TITLE
Save image in a loop

### ISSUE THREAD

**Issue by habi** [maartenbreddels/ipywebrtc#60]
I have a bunch of samples which I visualize with the [ITK widgets](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets). Saving out a screenshot one by one in a Jupyter notebook does work quite nicely
```
viewer = view(Cleaned[0].astype('uint8'))
viewer
```
```
image_recorder = ipywebrtc.ImageRecorder(stream=viewer, filename='samplename.png')
image_recorder
image_recorder.recording = True
image_recorder.autosave = True
```

Now I'd like to save screenshots of the 3D visualizations in a loop, but get no output at all.

```
Data['OutputName_3D'] = [os.path.join(f, sample + '_3D.png') for f, sample in zip(Data['Folder'], Data['Sample'])]
for c, row in Data.iterrows():
        # Start a viewer
        viewer = view(Cleaned[c].astype('uint8'))
        viewer
        # Save out
        image_recorder = ipywebrtc.ImageRecorder(stream=viewer, filename=row['OutputName_3D'])
        image_recorder
        image_recorder.recording = True
        image_recorder.autosave = True
```

Since I have about 25 samples I'd really like to loop through the saving part and not do it manually...
Can you give me a pointer on how to do achieve this?

**Comment by habi** [comment]
While trying to debug this, I found out that I have to wait until the `viewer` from the first cell is properly rendered before I'm able to use the `image_recorder` to save a file in the second cell.

**Comment by martinRenou** [comment]
That is one thing, another thing is that you cannot record new images in a Python loop. The only thing you can do is to make an event callback loop, I've helped someone doing it in this issue:
https://github.com/maartenbreddels/ipywebrtc/issues/54

**Comment by habi** [comment]
Thanks for the pointer, I'll try to see what I can do with the information from the other issue.
