### ISSUE TITLE
ipywebrtc not working for jupyterlab 1.2.3

### ISSUE THREAD

**Issue by ThomasDelteil** [maartenbreddels/ipywebrtc#66]
I am running jupyter lab `1.2.3` with python3
I installed the extension that way:
```
jupyter labextension install jupyter-webrtc
pip install ipywebrtc
```
When I run it in jupyterlab, the widgets don't render:
![Screen Shot 2019-11-25 at 11 44 00 AM](https://user-images.githubusercontent.com/3716307/69572430-f8083100-0f78-11ea-8cd2-bfbd67224b55.png)

did I miss an install step?

(it is working on the jupyter notebook)

**Comment by vidartf** [comment]
Did you install the ipywidgets extension for lab? `jupyter labextension install @jupyter-widgets/jupyterlab-manager`

**Comment by ThomasDelteil** [comment]
@vidartf, thanks that solved the issue 👍, should that be documented in the install instructions?

**Comment by martinRenou** [comment]
Indeed, it should

**Comment by martinRenou** [comment]
Actually I opened a PR for updating the README, I completely forgot about it :P
