### ISSUE TITLE
blank image when saving WidgetStream as PNG

### ISSUE THREAD

**Issue by giswqs** [maartenbreddels/ipywebrtc#81]
I followed the [Example with ipyleaflet: streaming of a map widget](https://ipywebrtc.readthedocs.io/en/latest/WidgetStream.html#Example-with-ipyleaflet:-streaming-of-a-map-widget) to save an ipyleaflet map as a PNG image. However, the result is a blank black image. The[ ImageRecorder documentation](https://ipywebrtc.readthedocs.io/en/latest/ImageRecorder.html) seems to have the same issue. Any advice? @maartenbreddels @martinRenou 
```
from ipyleaflet import Map
m = Map(center=(46, 14), zoom=5)
m

widget_stream = WidgetStream(widget=m, max_fps=1)
widget_stream

from ipywebrtc import WidgetStream, ImageRecorder
image_recorder = ImageRecorder(stream=widget_stream)
display(image_recorder)

```
![](https://i.imgur.com/mRwurZb.png)

**Comment by SylvainCorlay** [comment]
This may be a browser support issue. Are you using Safari?

**Comment by giswqs** [comment]
It appears to be browser issue. It does not work with Google Chrome, but works fine with Firefox. 

Google Chrome
![](https://i.imgur.com/HtKMBMd.png)

Firefox:
![](https://i.imgur.com/IERcuNF.png)
