### ISSUE TITLE
Widgets non functional in jupyterlab 2.x

### ISSUE THREAD

**Issue by str4w** [maartenbreddels/ipywebrtc#83]
After making a fresh install of jupyterlab 2.1.4, was unable to get ipywebrtc to work in lab, worked fine in notebook.

In notebook interface within jupyterlab, got following error.
Error displaying widget: model not found

On the console, errors of the form
blabla "not registered as a widget module"

These appeared to be traced back to the @jupyter-widgets/jupyterlab-manager being at version 2.0.0, which I think is the real source of the problem.  Further in the console log there was an error

"No provider for: jupyter.extensions.jupyterWidgetRegistry."

However, the only way I found to get the version of this extension down to 1.x was to downgrade jupyter.

**Comment by thewtex** [comment]
@martinRenou can this be related to the '@jupyter-widgets/base' dependency version?

**Comment by martinRenou** [comment]
Yes we never took time to enable JupyterLab 2, the JS tests needs to be fixed for JLab 2

**Comment by Raska** [comment]
Hello,
Same problem here but with JupyterLab v2.2.8.
Thank you for your help !

**Comment by maartenbreddels** [comment]
I'm assuming everybody moved on to jupyter lab 3, where it's working.
