### ISSUE TITLE
remote jupyter notebook server and recording using camera stream 

### ISSUE THREAD

**Issue by sathayen** [maartenbreddels/ipywebrtc#84]
I am using ipywebrtc on my local jupyter notebook to record an audio.  For this I am using the audio option from the CameraStream. This works just fine. 

But if I run the Jupyter notebook server on a remote machine (with --no-browser option)  and then just export the display on my local machine, the recording does not work.  It is probably trying to access the camera/microphone on that remote server. 

Is there a  way I can still use this library in such remote setup?  (ask it to use my local audio/video device)

**Comment by SylvainCorlay** [comment]
> It is probably trying to access the camera/microphone on that remote server.

The camera / microphone that is used is actually browser side.

I think there is another issue.

**Comment by sathayen** [comment]
Thanks @SylvainCorlay , in the ssh tunnel from my local machine to remote , I had a command line argument that was preventing the microphone access. I changed the ssh command to `ssh -L 8080:localhost:<port> <remote_user>@<remote_host>` and it worked fine. Thanks again.
