### ISSUE TITLE
Error displaying widgt:model not found

### ISSUE THREAD

**Issue by zhiujn** [maartenbreddels/ipywebrtc#91]
Uncaught（in promise）Error： Module jupyter-webrtc，manager.js：319 semver range ~0.5.0 is not registered as a widget module ad WidgetManager.loadClass (manager.js:319) at WidgetManager.<anonymous> at step at Object.next

I get above error in my jupyter lab width code:
from ipywebrtc import VideoStream
video = VideoStream.from_url("local mp3 file")
video

my soft version is:
jupyter code : 4.6.3
jupyter-notobook:6.0.3
ipython:7.13.0
ipykernel:5.2.1
jupyter client:6.1.3
jupyter lab:2.1.0
nbconvert:5.6.1
ipywidgets:7.5.1
ipywebrtc:0.5.0
jupyterlab-server:1.1.1

please help me! thank you

**Comment by arkanoid87** [comment]
same here: Error: Module jupyter-webrtc, semver range ~0.5.0 is not registered as a widget

$ python --version
`Python 3.7.6`

$ node --version
`v13.13.0`

$ jupyter lab --version
`2.1.2`

$ conda list ipywebrtc
```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
ipywebrtc                 0.5.0                    py37_0    conda-forge
```

$ jupyter labextension list
```
JupyterLab v2.1.2
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/hub-extension v2.1.2 disabled OK
        @pyviz/jupyterlab_pyviz v1.0.4  enabled  OK
        bqplot v0.5.16  enabled  OK
        ipyvolume v0.6.0-alpha.5  enabled  OK
        jupyter-leaflet v0.13.2  enabled  OK
        jupyter-matplotlib v0.7.3  enabled  OK
        jupyter-threejs v2.2.0  enabled  OK
        jupyter-vue v1.4.0  enabled  OK
        jupyter-webrtc v0.5.0  enabled  OK
        jupyterlab-datawidgets v6.3.0  enabled  OK
        jupyterlab_bokeh v1.0.0  enabled   X
```

$ conda info
```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
                          /home/jovyan/.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-106-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

code I've been trying to execute: https://github.com/jupyter-widgets/pythreejs/blob/master/examples/Capture.ipynb

maybe related to this other "model not found error" I've got into your ipyvolume project: https://github.com/maartenbreddels/ipyvolume/issues/345

**Comment by maartenbreddels** [comment]
My guess is that you opened the notebook from the documentation, those contained serialized models of the widgets with old version numbers.
I've removed those widgets from the notebook, so it shouldn't happen again.

**Comment by kizunasunhy** [comment]
I got the reason! It's because the environment you launch the jupyter lab and the kernel environment is different! Say you have 2 conda envs: env1 and env2, then you should launch jupyter and use the kernel both in env1 or env2. That will fix this problem.
![image](https://github.com/maartenbreddels/ipywebrtc/assets/24692121/529fec6e-c138-41f6-8022-39490bde4d43)
