### ISSUE TITLE
JupyterLab 2.x

### ISSUE THREAD

**Issue by alecapu80** [maartenbreddels/ipywebrtc#94]
When will be compatible with JupyterLab 2.x?
Thank you!

**Comment by maartenbreddels** [comment]
Hi,

I think it's better to wait to 3.0, so we can make it pip installable without a build phase.

**Comment by alecapu80** [comment]
Is compatible with 3.0 pre-lease?

**Comment by alecapu80** [comment]
I've reverted to Version 1.2.18
but I've also an issue:

Failed validating settings (@jupyterlab/extensionmanager-extension:plugin): Additional properties are not allowed ('disclaimed' was unexpected)
    
    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
         'description': 'Extension manager settings.',
         'jupyter.lab.setting-icon-class': 'jp-SettingsIcon',
         'jupyter.lab.setting-icon-label': 'Extension Manager',
         'properties': {'enabled': {'default': False,
                                    'description': 'Enables extension manager '
                                                   '(requires Node.js/npm).\n'
                                                   'WARNING: installing '
                                                   'untrusted extensions may '
                                                   'be unsafe.',
                                    'title': 'Enabled Status',
                                    'type': 'boolean'}},
         'title': 'Extension Manager',
         'type': 'object'}
    
    On instance:
        {'disclaimed': True}

**Comment by nmstoker** [comment]
@maartenbreddels is there any news on this, given that Jupyter Lab 3.0 was released in January? (this is definitely _not_ meant as a nag, just a eager follow up as being able to use this in 3.0 would be great 🙂 )

**Comment by maartenbreddels** [comment]
I started working on it in https://github.com/maartenbreddels/ipywebrtc/pull/95 but it requires a change in jupyter lab

**Comment by maartenbreddels** [comment]
3.0 is supported.
